`ifndef __GLOBALS__
`define __GLOBALS__

// Reference data files (generated by C software model)
localparam string RAD_FILE_NAME = "rad.txt";
localparam string SIN_FILE_NAME = "sin.txt";
localparam string COS_FILE_NAME = "cos.txt";

// RTL output files (generated by simulation for visual comparison)
localparam string OUT_RAD_FILE_NAME = "out_rad.txt";
localparam string OUT_SIN_FILE_NAME = "out_sin.txt";
localparam string OUT_COS_FILE_NAME = "out_cos.txt";

// UVM Globals for CORDIC
localparam int NUM_THETA     = 721;           // -360 to 360 degrees inclusive
localparam int CLOCK_PERIOD  = 10;            // 10ns = 100MHz
localparam int CORDIC_BITS   = 14;
localparam int CORDIC_QUANT  = (1 << CORDIC_BITS); // 16384

// CORDIC constants (must match C code exactly)
localparam int signed CORDIC_PI_SW      = 51471;
localparam int signed CORDIC_TWO_PI_SW  = 102943;
localparam int signed CORDIC_HALF_PI_SW = 25735;
localparam int signed CORDIC_1K_SW      = 9949;

// CORDIC lookup table (same as C code)
localparam shortint signed SW_CORDIC_TABLE [0:15] = '{
    16'sh3243, 16'sh1DAC, 16'sh0FAD, 16'sh07F5,
    16'sh03FE, 16'sh01FF, 16'sh00FF, 16'sh007F,
    16'sh003F, 16'sh001F, 16'sh000F, 16'sh0007,
    16'sh0003, 16'sh0001, 16'sh0000, 16'sh0000
};

// Software CORDIC model (replicates C code behavior exactly in SV)
// Used as secondary verification; primary check is against C-generated files
function automatic void cordic_sw(
    input  int signed  rad,
    output shortint signed sin_val,
    output shortint signed cos_val
);
    shortint signed x, y, z;
    int signed r;
    shortint signed d, tx, ty, tz;

    x = shortint'(CORDIC_1K_SW);
    y = 16'sh0000;
    r = rad;

    // Range reduction: bring into [-PI, PI]
    while (r > CORDIC_PI_SW)  r = r - CORDIC_TWO_PI_SW;
    while (r < -CORDIC_PI_SW) r = r + CORDIC_TWO_PI_SW;

    // Quadrant adjustment: bring into [-PI/2, PI/2]
    if (r > CORDIC_HALF_PI_SW) begin
        r = r - CORDIC_PI_SW;
        x = -x;
        y = -y;
    end else if (r < -CORDIC_HALF_PI_SW) begin
        r = r + CORDIC_PI_SW;
        x = -x;
        y = -y;
    end

    z = shortint'(r);

    // 16 CORDIC iterations
    for (int k = 0; k < 16; k++) begin
        d = (z >= 0) ? 16'sh0000 : 16'shFFFF;
        tx = x - (((y >>> k) ^ d) - d);
        ty = y + (((x >>> k) ^ d) - d);
        tz = z - ((SW_CORDIC_TABLE[k] ^ d) - d);
        x = tx;
        y = ty;
        z = tz;
    end

    cos_val = x;
    sin_val = y;
endfunction

`endif
